import matplotlib.pyplot as plt
from main import encrypt

# 10000 bytes of lorem ipsum text
text = b"""Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vitae ligula vestibulum, aliquet ante vitae, pulvinar orci. Vestibulum eu hendrerit elit. Quisque volutpat auctor felis, sed fermentum quam lobortis vitae. Maecenas tempus magna a enim gravida pharetra. Ut pulvinar iaculis vehicula. Etiam eget velit tincidunt, volutpat lorem ut, fermentum sem. Vestibulum eu erat nisi. Donec et neque egestas, dapibus tellus vitae, faucibus sapien. Phasellus finibus volutpat ipsum sed euismod.
Sed ac eros aliquet, lobortis nibh ac, faucibus diam. Pellentesque non consectetur lorem. Sed id placerat ex. Nam sit amet iaculis purus, consequat tristique ipsum. Integer pellentesque leo sed erat porta consectetur. Donec efficitur vehicula nunc, ut interdum metus. Donec et velit tempor, vulputate mauris in, molestie lectus. Morbi eget ipsum et eros scelerisque tempor non ut eros.
Integer ac lorem vel lacus consectetur porta. Duis id risus magna. Vivamus tempor dignissim ex eget tristique. Suspendisse condimentum diam consectetur rhoncus eleifend. Integer lacus arcu, vehicula eget metus nec, accumsan porttitor dui. Donec a leo mi. Pellentesque venenatis nunc at ipsum rhoncus, vitae pharetra turpis euismod. Praesent nec tortor vitae lorem viverra placerat quis non turpis. Nulla id leo id risus condimentum luctus non id diam.
Phasellus euismod non mi in finibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec vitae magna arcu. Morbi velit odio, ornare fermentum ullamcorper id, iaculis et odio. Mauris dignissim magna in malesuada venenatis. Sed quis dui viverra, suscipit nisi a, vestibulum est. Sed suscipit elementum orci ullamcorper tincidunt. Morbi in tortor sapien. Sed at arcu augue. Integer ac sapien sapien. Cras a nunc massa. Mauris at accumsan leo, id tempor purus.
Aenean in nulla elit. Donec vehicula diam magna. Nam euismod dignissim purus finibus condimentum. Suspendisse mauris tortor, tempus eu quam viverra, dictum dictum eros. Integer id feugiat nisl. Nam non dui ullamcorper, vestibulum diam vitae, porttitor neque. Curabitur nec laoreet nisi, in volutpat nulla. In ac eros sed leo mollis consectetur ut eu mi.
Donec est magna, sagittis non gravida nec, gravida eu enim. Nam sit amet commodo velit. Integer sed lacus ornare, venenatis ligula eu, congue turpis. Donec porttitor suscipit congue. Phasellus placerat est in justo congue egestas. Cras id orci felis. Integer vitae tellus blandit, tristique nibh id, malesuada eros. Phasellus sed felis vel turpis fringilla sagittis. Duis placerat imperdiet bibendum. Quisque efficitur augue vitae sem hendrerit, ac volutpat sem imperdiet. Vestibulum neque enim, aliquam sit amet ipsum id, placerat dignissim arcu.
Aenean vehicula justo sit amet tempor malesuada. Nunc faucibus dignissim augue, et efficitur tortor mollis non. Mauris metus dui, viverra quis lorem ac, ullamcorper pellentesque sem. Praesent ac orci imperdiet, elementum magna et, semper nisl. Ut condimentum justo sit amet fermentum dignissim. Quisque sit amet neque sed leo ultrices vestibulum id at magna. Duis ac tempor ante. Pellentesque fermentum pharetra leo, ac pellentesque quam porttitor nec. Praesent vestibulum, nibh in laoreet suscipit, enim nisi tincidunt leo, non luctus lectus lectus ac sem. Proin et maximus mauris, quis fringilla purus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed eget risus feugiat, sagittis lacus at, consequat erat. Donec efficitur ante at lorem molestie vestibulum. Aliquam aliquam urna sed lectus tincidunt maximus.
Suspendisse ac lectus eu ipsum tristique vulputate. Aliquam ut nunc in turpis commodo placerat viverra quis dolor. In ut vehicula mauris. Fusce maximus augue sit amet magna accumsan facilisis. Sed cursus, leo vel pharetra fringilla, ante nunc fermentum ipsum, sed porttitor nisi mi at velit. Donec sed lacus scelerisque, fringilla tellus a, tristique leo. Maecenas sodales sapien at aliquet mattis. Mauris rhoncus orci neque, a tempus sapien accumsan non.
Donec ac metus sed odio aliquam rhoncus. Donec bibendum dui vitae nunc accumsan, eleifend interdum mi vestibulum. Praesent ut lectus eget quam elementum molestie at ut nisi. Quisque fringilla scelerisque venenatis. Mauris eleifend consectetur augue, sit amet semper sem venenatis vel. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc mauris nisi, volutpat quis nisi sed, sagittis suscipit nulla. Curabitur sollicitudin nulla ut mattis pulvinar. In rutrum nisl ut urna vehicula bibendum. Suspendisse potenti. Aliquam et eleifend est, ac vehicula diam. Maecenas placerat eros nec massa lacinia faucibus. Proin ut massa elit. Aliquam id enim semper, pharetra dolor in, aliquam arcu.
Quisque eu rutrum nibh. Vestibulum at nunc nec augue mollis vulputate eget quis mi. Etiam scelerisque eleifend nisl, in interdum libero dictum nec. Donec fermentum in eros ut hendrerit. Praesent at neque gravida elit dictum faucibus. Maecenas tincidunt nulla quis risus feugiat, et iaculis leo gravida. Vestibulum dictum mauris velit, a sollicitudin tellus scelerisque quis. Aenean eu molestie nibh. Phasellus sapien enim, convallis at eleifend at, ullamcorper at diam. Duis sit amet mollis nunc. Aenean ut euismod ex. Etiam aliquam, sapien ac ullamcorper efficitur, libero nisi suscipit quam, eget finibus est ex at nulla.
Donec elit leo, scelerisque ut odio a, consequat placerat lacus. Mauris sed consectetur ante. Vivamus volutpat leo nulla, quis dapibus purus dictum nec. Praesent consectetur in lorem venenatis accumsan. Cras vel posuere justo, in rutrum tortor. Donec augue ante, sagittis lacinia efficitur quis, efficitur sed justo. Curabitur lacinia pulvinar ligula, in vulputate nibh ornare non. In nec congue lacus. Vestibulum non cursus velit. Aliquam erat sem, efficitur vel elit ut, euismod tempus eros. Etiam porttitor arcu nec neque rutrum, eu rutrum diam faucibus. Suspendisse potenti. Donec eget maximus metus.
Fusce sed auctor urna, et gravida sapien. Praesent volutpat suscipit erat sit amet consequat. Curabitur sagittis varius quam, a consequat libero condimentum eget. Morbi eu libero sit amet nulla malesuada bibendum. Nunc at leo at lectus pretium porta. Nullam ut ipsum efficitur leo varius sodales. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean scelerisque, sem a tempus convallis, tortor lacus dapibus mi, a pharetra nunc lectus sollicitudin libero. Nunc et ante lectus. Nulla sem sapien, auctor eget purus sit amet, rutrum gravida eros. In nec tincidunt nulla, ut dignissim ante. Morbi blandit pretium fringilla. Phasellus et augue mattis, accumsan lacus eget, ornare nisi.
Vestibulum tortor enim, dictum at consequat sed, commodo quis elit. In euismod metus sed nulla placerat, vel eleifend odio fringilla. Suspendisse semper sollicitudin ultricies. Donec id mi orci. Donec pharetra nulla ut leo elementum sollicitudin. Vestibulum vel convallis arcu. Sed mattis risus nec mauris dictum, a dictum magna venenatis. Nullam hendrerit pellentesque nulla, eget tincidunt lorem suscipit vel.
In hac habitasse platea dictumst. Nunc maximus mauris id maximus viverra. Nunc maximus maximus condimentum. Sed eu massa magna. Fusce nunc ipsum, bibendum ac quam quis, iaculis ultrices dolor. Nulla pulvinar posuere felis, non venenatis est fringilla vel. Cras dictum ultrices eros, vel laoreet lorem vulputate eu. Etiam dapibus nec sapien vel placerat. Fusce id iaculis diam. Praesent vehicula congue tortor sit amet vehicula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
Phasellus tellus libero, suscipit sed luctus vel, auctor eget nisl. Aliquam suscipit pellentesque dui, vel lacinia eros interdum sit amet. Suspendisse ut metus vel elit scelerisque porttitor. Pellentesque auctor semper quam vel sollicitudin. Vivamus efficitur magna sit amet vulputate pellentesque. Ut quis nunc tincidunt, vehicula mi in, malesuada diam. Fusce id purus accumsan, imperdiet ligula eget, dignissim elit. Praesent a hendrerit erat. Duis lorem risus, placerat sit amet tellus et, tincidunt faucibus eros. Proin auctor felis volutpat tellus ultrices, eget scelerisque arcu commodo. Sed et egestas mauris, a eleifend purus. Etiam ex nisi, pulvinar at blandit sit amet, fermentum ornare purus.
Duis nisi eros, finibus ut rhoncus nec, sodales et magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur volutpat urna id massa accumsan, vel consequat felis imperdiet. Nunc massa augue, bibendum non urna in, sodales dignissim odio. Nam neque urna, pharetra eget porttitor at, vulputate nec nibh. Donec ac mauris in magna tincidunt pretium. Nunc erat nunc, fermentum a blandit at, congue sed mauris. Aenean tempus risus quis pretium tempor. Nullam interdum leo a mi cursus aliquet. Pellentesque nec scelerisque purus. Cras sollicitudin sit amet nisl vel malesuada. Sed non pulvinar massa. Aliquam imperdiet vulputate lacus a commodo. In accumsan porttitor vestibulum. Morbi iaculis congue leo, nec varius eros fringilla fermentum. Nunc magna nisl, ultrices non mauris eu, mollis commodo enim.
Etiam egestas faucibus nibh pretium gravida. Quisque dictum lacinia interdum. Vivamus id diam purus. Phasellus nec nulla lectus. Curabitur tincidunt eros turpis, semper laoreet est elementum et. Etiam finibus odio nec turpis ultrices, non ornare ante porta. Aliquam volutpat porta nisi, non cursus urna viverra in. Curabitur ut elit elit. Etiam eget laoreet dolor. Mauris laoreet quam est. Phasellus viverra ut leo ut dictum. Vestibulum lectus ipsum, ultrices in diam vitae, consectetur auctor urna.
Sed tristique tortor eu sodales tristique. Nunc hendrerit leo nibh, vitae fermentum eros vulputate ut. Etiam pharetra porta risus, vitae eleifend erat sollicitudin et. Suspendisse tellus turpis, rutrum a blandit eget, maximus quis ipsum. Quisque ante justo, posuere non enim sit amet, facilisis facilisis purus. Sed justo metus, consequat sed luctus at donec.""" 

def letter_freq(text):
    freq = [0 for _ in range(256)]
    for c in text:
        freq[ord(c)] += 1
    return freq

def plot_letter_freq(text):
    freq = letter_freq(text)
    plt.bar(range(256), freq)
    plt.show()

plot_letter_freq(text)
ciphertext = encrypt(text, b"kriptografi")
ciphertext = ciphertext.decode("latin-1")
plot_letter_freq(ciphertext)